apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: mysql-k8s-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: mysql-credentials-1
