apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-kaniko-sa
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - sleep
    args:
    - 99d
    env:
    - name: AWS_DEFAULT_REGION
      value: "us-east-1"
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/workspace
  - name: git
    image: alpine/git:latest
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/workspace
  - name: jnlp
    image: jenkins/inbound-agent:3309.v27b_9314fd1a_4-1
    env:
    - name: JENKINS_URL
      value: http://jenkins.jenkins.svc.cluster.local:8080/
    - name: JENKINS_TUNNEL
      value: jenkins.jenkins.svc.cluster.local:50000
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/workspace
  volumes:
  - name: workspace-volume
    emptyDir: {}