apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: mysql-k8s-secret
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: mysql-credentials-secret
        property: mysql-root-password
    - secretKey: mysql_hostname
      remoteRef:
        key: mysql-credentials-secret
        property: mysql_hostname
    - secretKey: mysql-username
      remoteRef:
        key: mysql-credentials-secret
        property: mysql-username
    - secretKey: mysql-password
      remoteRef:
        key: mysql-credentials-secret
        property: mysql-password
    - secretKey: mysql_port
      remoteRef:
        key: mysql-credentials-secret
        property: mysql_port