apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: redis-k8s-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: redis-credentials-secret
