# serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-kaniko-sa
  namespace: jenkins
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::339007232055:role/jenkins-kaniko-role
---
# clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-kaniko-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "persistentvolumeclaims", "events"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
# clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-kaniko-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-kaniko-role
subjects:
- kind: ServiceAccount
  name: jenkins-kaniko-sa
  namespace: jenkins