controller:
  image:
    repository: jenkins/jenkins
    tag: lts-jdk17
  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true

  installPlugins:
    - kubernetes:1.31
    - workflow-aggregator:2.6
    - git:5.14.4
    - configuration-as-code:1954.v57a_5e1f7e_2023-11-01
    - credentials:184.v5d2b_aac
    - plain-credentials:1.8
    - amazon-ecr:1.7
    - docker-workflow:563.vd5d2e5c4007f
    - pipeline-utility-steps:2.26

  jenkinsUrl: http://jenkins.jenkins.svc.cluster.local:8080
  agent:
    podTemplates:
      kaniko:
        label: kaniko
        containers:
          - name: kaniko
            image: gcr.io/kaniko-project/executor:latest
            command: ["/busybox/sh", "-c"]
            args:
              - >
                /kaniko/executor
                --dockerfile=/workspace/Dockerfile
                --context=/workspace
                --destination=$(DESTINATION_IMAGE)
                --insecure
                --skip-tls-verify
            volumeMounts:
              - name: kaniko-secret
                mountPath: /kaniko/.docker
        volumes:
          - name: kaniko-secret
            secret:
              secretName: regcred

  serviceAccount:
    create: false
    name: jenkins-kaniko-sa
    
  serviceType: loadBalancer


  persistence:
    enabled: true
    storageClass: gp3
    accessModes:
      - ReadWriteOnce
    annotations: {}
    size: 8Gi

rbac:
  create: true