controller:
  image:
    repository: jenkins/jenkins
    tag: lts-jdk17
  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  installPlugins:
    - kubernetes:4029.v5712230ccb_f8
    - workflow-aggregator:596.v8c21c963d92d
    - git:5.0.0
    - configuration-as-code:1625.v27444588cc3d
    - credentials:1271.v54b_1c1c6388a_
    - plain-credentials:143.v1b_df8b_d3b_e48
    - amazon-ecr:1.7
    - docker-workflow:563.vd5d2e5c4007f
    - pipeline-utility-steps:2.13.0
  jenkinsUrl: http://jenkins.jenkins.svc.cluster.local:8080
  
  
  serviceAccount:
    create: false
    name: jenkins-kaniko-sa
    
  serviceType: LoadBalancer
  persistence:
    enabled: true
    storageClass: "gp3"
    accessModes:
      - ReadWriteOnce
    size: 8Gi

rbac:
  create: true

agent:
  enabled: true